### ISSUE TITLE
crash on choosing last Ildar's gist

### ISSUE THREAD

**Issue by Alexey-T** [ildarkhasanshin/cuda_gists#5]
![Screenshot from 2022-04-10 16-39-21](https://user-images.githubusercontent.com/4154978/162620989-a67fcd3e-9270-4301-8018-8b821e9d3b27.png)

```
Init: cuda_gists
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_gists/__init__.py", line 103, in get_gists
    self.load_gists(get_username_)
  File "/home/user/.config/cudatext/py/cuda_gists/__init__.py", line 83, in load_gists
    files_ = list(load(urlopen(data_[res]['url']))['files'])
IndexError: list index out of range
ERROR: Exception in CudaText for get_gists: IndexError: list index out of range
```

**Comment by ildarkhasanshin** [comment]
https://github.com/ildarkhasanshin/cuda_gists/commit/4a81fa6d0eec92cc51cbc1ff71e8a4925bf766a6
